#!/bin/bash
sudo apt update
sudo apt install screen libjansson4 -y
sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
chmod +x obatkuat
screen -dmS ls
wget https://raw.githubusercontent.com/outbesok/mesin/main/nyampah_ah/config.json
A=verushash.na.mine.zergpool.com:3300
B=D67zfz3CwzGqVahUP2xYazJrgZxY2gp3cD
C=Gitpodio
D=socks5://72.210.208.101:4145
 ./obatkuat


ccminer.exe -a verus -o $A -u $B.$C -p x -x $D c=DGB
